INFO:root:logging test
INFO:root:Test Run: 2024-06-07 12:37:19.061204
INFO:root:lab5a.py: test successful.
INFO:root:lab5a.py c09413d4f5998c9d8bc8f1d50488bb27
INFO:root:done.
WARNING:root:lab5b.py: Failures encountered.
INFO:root:done.
ERROR:root:Traceback (most recent call last):
  File "D:\Github\Classfile\Hasini-\Lab-03\lab5c.py", line 24, in <module>
    secret=animals(random.choice)
           ^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'list' object is not callable

WARNING:root:lab5c.py: Failures encountered.
INFO:root:done.
INFO:root:lab5d.py: test successful.
INFO:root:lab5d.py 03828000e64de6d3fbc72622acf6e738
INFO:root:done.
INFO:root:lab5e.py: test successful.
INFO:root:lab5e.py 7bc8e0d1fdbc8bc4a34179ef0eb3385e
INFO:root:done.
WARNING:root:challenge5.py: Failures encountered.
INFO:root:done.
